#!/bin/bash

# bash /home/bnguyen/Desktop/DE_project/DB_mig/raw_storage_migration

jupyter nbconvert --to notebook --execute --inplace /home/bnguyen/Desktop/DE_project/notebooks/parquet_converter.ipynb
jupyter nbconvert --to notebook --execute --inplace /home/bnguyen/Desktop/DE_project/notebooks/table_filter.ipynb
jupyter nbconvert --to notebook --execute --inplace /home/bnguyen/Desktop/DE_project/notebooks/dw_load.ipynb

# chmod +x <link>
# ./pipeline