#!/bin/bash

bash /path/to/your/DB_mig/raw_storage_migration

jupyter nbconvert --to notebook --execute --inplace /path/to/your/notebooks/parquet_converter.ipynb
jupyter nbconvert --to notebook --execute --inplace /path/to/your/notebooks/table_filter.ipynb
jupyter nbconvert --to notebook --execute --inplace /path/to/your/notebooks/dw_load.ipynb

# chmod +x <link>
# ./run_all